name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64


    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build the Docker image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64 -t pyrinpyi/pyipad-stratum-bridge:latest --progress=plain --push .
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pyrinpyi/pyipad-stratum-bridge:latest

